//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

import java.util.HashMap;

public class EventWithArrayTypes extends Event {
    private EventWithArrayTypes(Builder builder) {
        super("Event With Array Types", builder.properties);
    }

    /**
     * description for required boolean array
     * <p>
     * Must be followed by {@link IRequiredNumberArray#requiredNumberArray(Double[])
     */
    public static IRequiredNumberArray requiredBooleanArray(Boolean[] requiredBooleanArray) {
        Builder builder = new Builder();
        builder.properties.put("requiredBooleanArray", requiredBooleanArray);
        return builder;
    }

    // Inner Builder class with required properties
    public static class Builder implements IRequiredNumberArray, IRequiredObjectArray, IRequiredStringArray, IBuild {
        private final HashMap<String, Object> properties = new HashMap<>();

        private Builder() {

        }

        /**
         * Description for required number array
         * <p>
         * Must be followed by {@link IRequiredObjectArray#requiredObjectArray(org.json.JSONObject[])
         */
        public IRequiredObjectArray requiredNumberArray(Double[] requiredNumberArray) {
            this.properties.put("requiredNumberArray", requiredNumberArray);
            return this;
        }

        /**
         * Description for required object array
         * <p>
         * Must be followed by {@link IRequiredStringArray#requiredStringArray(String[])
         */
        public IRequiredStringArray requiredObjectArray(org.json.JSONObject[] requiredObjectArray) {
            this.properties.put("requiredObjectArray", requiredObjectArray);
            return this;
        }

        /**
         * description for required string array
         * <p>
         * Must be followed by by additional optional properties or build() method
         */
        public IBuild requiredStringArray(String[] requiredStringArray) {
            this.properties.put("requiredStringArray", requiredStringArray);
            return this;
        }

        public EventWithArrayTypes build() {
            return new EventWithArrayTypes(this);
        }
    }

    // Required property interfaces
    public interface IRequiredNumberArray {
        IRequiredObjectArray requiredNumberArray(Double[] requiredNumberArray);
    }

    public interface IRequiredObjectArray {
        IRequiredStringArray requiredObjectArray(org.json.JSONObject[] requiredObjectArray);
    }

    public interface IRequiredStringArray {
        IBuild requiredStringArray(String[] requiredStringArray);
    }

    /** Build interface with optional properties */
    public interface IBuild {
        EventWithArrayTypes build();
    }
}
