//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

public class EventWithDifferentCasingTypes extends Event {
    public EventWithDifferentCasingTypes(
        EventWithDifferentCasingTypesProperties eventProperties
    ) {
        super("event withDifferent_CasingTypes");
        this.addProperty("enumCamelCase", eventProperties.getEnumCamelCase().toValue());
        this.addProperty("EnumPascalCase", eventProperties.getEnumPascalCase().toValue());
        this.addProperty("enum_snake_case", eventProperties.getEnumSnakeCase().toValue());
        this.addProperty("enum with space", eventProperties.getEnumWithSpace().toValue());
        this.addProperty("propertyWithCamelCase", eventProperties.getPropertyWithCamelCase());
        this.addProperty("PropertyWithPascalCase", eventProperties.getPropertyWithPascalCase());
        this.addProperty("property_with_snake_case", eventProperties.getPropertyWithSnakeCase());
        this.addProperty("property with space", eventProperties.getPropertyWithSpace());
    }
}
