//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

/**
 * Description for case with space
 */
public class EventWithDifferentCasingTypesProperties {
    private EventWithDifferentCasingTypesEnumWithSpace enumWithSpace;
    private EventWithDifferentCasingTypesEnumSnakeCase enumSnakeCase;
    private EventWithDifferentCasingTypesEnumCamelCase enumCamelCase;
    private EventWithDifferentCasingTypesEnumPascalCase enumPascalCase;
    private String propertyWithSpace;
    private String propertyWithSnakeCase;
    private String propertyWithCamelCase;
    private String propertyWithPascalCase;

    /**
     * Description for enum with space
     */
    public EventWithDifferentCasingTypesEnumWithSpace getEnumWithSpace() { return enumWithSpace; }
    public void setEnumWithSpace(EventWithDifferentCasingTypesEnumWithSpace value) { this.enumWithSpace = value; }

    /**
     * description_for_enum_snake_case
     */
    public EventWithDifferentCasingTypesEnumSnakeCase getEnumSnakeCase() { return enumSnakeCase; }
    public void setEnumSnakeCase(EventWithDifferentCasingTypesEnumSnakeCase value) { this.enumSnakeCase = value; }

    /**
     * descriptionForEnumCamelCase
     */
    public EventWithDifferentCasingTypesEnumCamelCase getEnumCamelCase() { return enumCamelCase; }
    public void setEnumCamelCase(EventWithDifferentCasingTypesEnumCamelCase value) { this.enumCamelCase = value; }

    /**
     * DescirptionForEnumPascalCase
     */
    public EventWithDifferentCasingTypesEnumPascalCase getEnumPascalCase() { return enumPascalCase; }
    public void setEnumPascalCase(EventWithDifferentCasingTypesEnumPascalCase value) { this.enumPascalCase = value; }

    /**
     * Description for case with space
     */
    public String getPropertyWithSpace() { return propertyWithSpace; }
    public void setPropertyWithSpace(String value) { this.propertyWithSpace = value; }

    /**
     * Description_for_snake_case
     */
    public String getPropertyWithSnakeCase() { return propertyWithSnakeCase; }
    public void setPropertyWithSnakeCase(String value) { this.propertyWithSnakeCase = value; }

    /**
     * descriptionForCamelCase
     */
    public String getPropertyWithCamelCase() { return propertyWithCamelCase; }
    public void setPropertyWithCamelCase(String value) { this.propertyWithCamelCase = value; }

    /**
     * DescriptionForPascalCase
     */
    public String getPropertyWithPascalCase() { return propertyWithPascalCase; }
    public void setPropertyWithPascalCase(String value) { this.propertyWithPascalCase = value; }
}
