//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

/**
 * Description for event with Array Types
 */
public class EventWithArrayTypesProperties {
    private boolean[] requiredBooleanArray;
    private double[] requiredNumberArray;
    private Object[] requiredObjectArray;
    private String[] requiredStringArray;

    /**
     * description for required boolean array
     */
    public boolean[] getRequiredBooleanArray() { return requiredBooleanArray; }
    public void setRequiredBooleanArray(boolean[] value) { this.requiredBooleanArray = value; }

    /**
     * Description for required number array
     */
    public double[] getRequiredNumberArray() { return requiredNumberArray; }
    public void setRequiredNumberArray(double[] value) { this.requiredNumberArray = value; }

    /**
     * Description for required object array
     */
    public Object[] getRequiredObjectArray() { return requiredObjectArray; }
    public void setRequiredObjectArray(Object[] value) { this.requiredObjectArray = value; }

    /**
     * description for required string array
     */
    public String[] getRequiredStringArray() { return requiredStringArray; }
    public void setRequiredStringArray(String[] value) { this.requiredStringArray = value; }
}
