//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

import java.io.IOException;

/**
 * Event 2 Property - Enum
 */
public enum EventWithAllPropertiesRequiredEnum {
    ENUM1, ENUM2;

    public String toValue() {
        switch (this) {
            case ENUM1: return "Enum1";
            case ENUM2: return "Enum2";
        }
        return null;
    }

    public static EventWithAllPropertiesRequiredEnum forValue(String value) throws IOException {
        if (value.equals("Enum1")) return ENUM1;
        if (value.equals("Enum2")) return ENUM2;
        throw new IOException("Cannot deserialize EventWithAllPropertiesRequiredEnum");
    }
}
