//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

import java.io.IOException;

/**
 * Description for required enum
 */
public enum EventWithEnumTypesOptionalEnum {
    OPTIONAL_ENUM_1, OPTIONAL_ENUM_2;

    public String toValue() {
        switch (this) {
            case OPTIONAL_ENUM_1: return "optional enum 1";
            case OPTIONAL_ENUM_2: return "optional enum 2";
        }
        return null;
    }

    public static EventWithEnumTypesOptionalEnum forValue(String value) throws IOException {
        if (value.equals("optional enum 1")) return OPTIONAL_ENUM_1;
        if (value.equals("optional enum 2")) return OPTIONAL_ENUM_2;
        throw new IOException("Cannot deserialize EventWithEnumTypesOptionalEnum");
    }
}
