//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

import java.io.IOException;

/**
 * Description for optional enum
 */
public enum RequiredEnumEnum {
    REQUIRED_ENUM_1, REQUIRED_ENUM_2;

    public String toValue() {
        switch (this) {
            case REQUIRED_ENUM_1: return "required enum 1";
            case REQUIRED_ENUM_2: return "required enum 2";
        }
        return null;
    }

    public static RequiredEnumEnum forValue(String value) throws IOException {
        if (value.equals("required enum 1")) return REQUIRED_ENUM_1;
        if (value.equals("required enum 2")) return REQUIRED_ENUM_2;
        throw new IOException("Cannot deserialize RequiredEnumEnum");
    }
}
