//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-jre-ampli'
//
// Required dependencies: com.amplitude:java-sdk:1.6.0, org.json:json:20201115
// Tracking Plan Version: 0
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-jre-ampli)
//
package com.amplitude.ampli;

import java.util.HashMap;

public class EventObjectTypes extends Event {
    private EventObjectTypes(Builder builder) {
        super("Event Object Types", builder.properties);
    }

    public static IRequiredObjectArray builder() { return new Builder(); }

    // Inner Builder class with required properties
    public static class Builder implements IRequiredObjectArray, IBuild {
        private final HashMap<String, Object> properties = new HashMap<>();

        private Builder() {
            this.properties.put("requiredObject", null);
        }

        /**
         * Property Object Array Type
         * <p>
         * Must be followed by by additional optional properties or build() method
         */
        public IBuild requiredObjectArray(Object[] requiredObjectArray) {
            this.properties.put("requiredObjectArray", requiredObjectArray);
            return this;
        }

        public EventObjectTypes build() {
            return new EventObjectTypes(this);
        }
    }

    // Required property interfaces
    public interface IRequiredObjectArray {
        IBuild requiredObjectArray(Object[] requiredObjectArray);
    }

    /** Build interface with optional properties */
    public interface IBuild {
        EventObjectTypes build();
    }
}
