//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-jre-ampli'
//
// Required dependencies: com.amplitude:java-sdk:1.6.0, org.json:json:20201115
// Tracking Plan Version: 0
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-jre-ampli)
//
package com.amplitude.ampli;

import com.amplitude.Amplitude;

public class LoadClientOptions {
    private String apiKey;
    private Amplitude instance;

    public LoadClientOptions() {
    }

    public LoadClientOptions setApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }

    public String getApiKey() { return this.apiKey; }

    public LoadClientOptions setInstance(Amplitude instance) {
        this.instance = instance;
        return this;
    }

    public Amplitude getInstance() { return this.instance; }
}
