//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli-v2'
//
// Required dependencies: com.amplitude:analytics-android:1.0.0
// Tracking Plan Version: 0
// Build: 1.0.0
// Runtime: android:java-ampli-v2
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli-v2)
//
package com.amplitude.ampli;

import com.amplitude.android.Configuration;
import com.amplitude.android.events.Plan;

public class DefaultConfiguration extends Configuration {
    public DefaultConfiguration(String apiKey, android.content.Context appContext, Plan defaultObservePlan) {
        super(apiKey, appContext.getApplicationContext());
        this.setPlan(defaultObservePlan);
    }
}
