def import_pods

pod 'Amplitude', :git => 'https://github.com/amplitude/Amplitude-iOS.git', :branch => 'middleware-support'

end

inhibit_all_warnings!

target 'AmpliSwiftSampleApp (iOS)' do
    project "AmpliSwiftSampleApp"
    platform :ios, '14.0'

    import_pods
end

target 'AmpliSwiftSampleApp (macOS)' do
    platform :macos, '12.0'
    project "AmpliSwiftSampleApp"

    import_pods
end

target 'AmpliSwiftSampleAppTests' do
    platform :ios, '14.0'
    project "AmpliSwiftSampleApp"

    import_pods
end
