//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.37.0, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
// Runtime: android:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

import java.util.Map;

public abstract class Event {
    final String eventType;
    final Map<String, Object> eventProperties;

    protected Event(String eventType, Map<String, Object> eventProperties) {
        this.eventType = eventType;
        this.eventProperties = eventProperties == null || eventProperties.isEmpty() ? null : eventProperties;
    }
}
