//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:[2.37.0,3.0), com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 1
// Build: 1.0.0
// Runtime: android:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

import java.util.HashMap;

public class EventWithOptionalArrayTypes extends Event {
    private EventWithOptionalArrayTypes(Builder builder) {
        super("Event With Optional Array Types", builder.properties);
    }

    public static IBuild builder() { return new Builder(); }

    // Inner Builder class with required properties
    public static class Builder implements IBuild {
        private final HashMap<String, Object> properties = new HashMap<>();

        private Builder() {

        }

        /**
         * Description for optional boolean array
         */
        public IBuild optionalBooleanArray(Boolean[] optionalBooleanArray) {
            this.properties.put("optionalBooleanArray", optionalBooleanArray);
            return this;
        }

        /**
         * Description for optional enum array
         */
        public IBuild optionalEnumArray(String[] optionalEnumArray) {
            this.properties.put("optionalEnumArray", optionalEnumArray);
            return this;
        }

        /**
         * Description for optional object array
         */
        public IBuild optionalJsonArray(Object[] optionalJsonArray) {
            this.properties.put("optionalJSONArray", optionalJsonArray);
            return this;
        }

        /**
         * Description for optional number array
         */
        public IBuild optionalNumberArray(Double[] optionalNumberArray) {
            this.properties.put("optionalNumberArray", optionalNumberArray);
            return this;
        }

        /**
         * Description for optional string array
         */
        public IBuild optionalStringArray(String[] optionalStringArray) {
            this.properties.put("optionalStringArray", optionalStringArray);
            return this;
        }

        public EventWithOptionalArrayTypes build() {
            return new EventWithOptionalArrayTypes(this);
        }
    }

    /** Build interface with optional properties */
    public interface IBuild {
        IBuild optionalBooleanArray(Boolean[] optionalBooleanArray);
        IBuild optionalEnumArray(String[] optionalEnumArray);
        IBuild optionalJsonArray(Object[] optionalJsonArray);
        IBuild optionalNumberArray(Double[] optionalNumberArray);
        IBuild optionalStringArray(String[] optionalStringArray);
        EventWithOptionalArrayTypes build();
    }
}
