name: Ampli Merge Check (ReactNative)

on:
  pull_request:
    paths:
      - 'react-native/javascript/**'
      - 'react-native/typescript/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amplitudeinc/ampli
    env:
      API_URL: https://data-api.staging.amplitude.com/graphql
      APP_URL: https://data.staging.amplitude.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: (ReactNative JS) Check the Data branch is merged before merging the Git branch
        working-directory: ./react-native/javascript/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (ReactNative TS) Check the Data branch is merged before merging the Git branch
        working-directory: react-native/typescript/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}
