name: Ampli Merge Check

on:
  pull_request:
    paths:
      - 'jre/java/**'
      - 'jre/kotlin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amplitudeinc/ampli
    timeout-minutes: 2

    env:
      API_URL: https://data-api.staging.amplitude.com/graphql
      APP_URL: https://data.staging.amplitude.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: (JRE Kotlin) Check the Data branch is merged before merging the Git branch
        working-directory: ./jre/kotlin/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (JRE Java) Check the Data branch is merged before merging the Git branch
        working-directory: ./jre/java/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}
