name: Ampli Merge Check (ReactNative V1)

on:
  pull_request:
    paths:
      - 'react-native/javascript/v1/**'
      - 'react-native/typescript/v1/**'

jobs:
  build:
    runs-on: self-hosted-2x8-x86-64
    container:
      image: amplitudeinc/ampli
    env:
      API_URL: https://data-api.staging.amplitude.com/graphql
      APP_URL: https://data.staging.amplitude.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: (ReactNative JS V1) Check the Data branch is merged before merging the Git branch
        working-directory: ./react-native/javascript/v1/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (ReactNative TS V1) Check the Data branch is merged before merging the Git branch
        working-directory: react-native/typescript/v1/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}
