name: Ampli Merge Check (Node V2)

on:
  pull_request:
    paths:
      - 'node/javascript/v2/**'
      - 'node/typescript/v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amplitudeinc/ampli
    env:
      API_URL: https://data-api.staging.amplitude.com/graphql
      APP_URL: https://data.staging.amplitude.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: (Node JS V2) Check the Data branch is merged before merging the Git branch
        working-directory: ./node/javascript/v2/AmpliApp
        run: ampli status --is-merged -t ${{ secrets.AMPLI_TOKEN }}

      - name: (Node TS V2) Check the Data branch is merged before merging the Git branch
        working-directory: ./node/typescript/v2/AmpliApp
        run: ampli status --is-merged -t ${{ secrets.AMPLI_TOKEN }}
