name: Ampli Merge Check (iOS)

on:
  pull_request:
    paths:
      - 'ios/objective-c/**'
      - 'ios/swift/**'

jobs:
  build:
    runs-on: self-hosted-2x8-x86-64
    container:
      image: amplitudeinc/ampli-swift
    env:
      API_URL: https://data-api.staging.amplitude.com/graphql
      APP_URL: https://data.staging.amplitude.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: (iOS Swift V1) Check the Data branch is merged before merging the Git branch
        working-directory: ./ios/swift/v1/AmpliSwiftSampleApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (iOS Swift V2) Check the Data branch is merged before merging the Git branch
        working-directory: ./ios/swift/v2/AmpliSwiftSampleApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (iOS Objective-C V1) Check the Data branch is merged before merging the Git branch
        working-directory: ./ios/objective-c/v1/AmpliObjectiveCSampleApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (iOS Objective-C V2) Check the Data branch is merged before merging the Git branch
        working-directory: ./ios/objective-c/v2/AmpliObjectiveCSampleApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}
