name: Ampli Merge Check (Android)

on:
  pull_request:
    paths:
      - 'android/kotlin/**'
      - 'android/java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amplitudeinc/ampli
    env:
      API_URL: https://data-api.staging.amplitude.com/graphql
      APP_URL: https://data.staging.amplitude.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: (Android Kotlin) Check the Data branch is merged before merging the Git branch
        working-directory: ./android/kotlin/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (Android Java) Check the Data branch is merged before merging the Git branch
        working-directory: ./android/java/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}
