name: Ampli Merge Check (Node V2)

on:
  pull_request:
    paths:
      - 'node/javascript/v2/**'
      - 'node/typescript/v2/**'

jobs:
  build:
    runs-on: self-hosted-2x8-x86-64
    container:
      image: amplitudeinc/ampli@sha256:99d093218ddcc96ea4eaf42997612af30d6337a6d0d0c21aa6292a9cfe5fc0d9
    env:
      API_URL: https://data-api.staging.amplitude.com/graphql
      APP_URL: https://data.staging.amplitude.com/

    steps:
      - name: Checkout repo
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: (Node JS V2) Check the Data branch is merged before merging the Git branch
        working-directory: ./node/javascript/v2/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}

      - name: (Node TS V2) Check the Data branch is merged before merging the Git branch
        working-directory: ./node/typescript/v2/AmpliApp
        run: ampli status --is-merged -t ${{secrets.AMPLI_TOKEN}}
