name: CI - JS/TS V1 Tests

on:
  pull_request:
    paths:
      - 'browser/javascript/v1/**'
      - 'browser/typescript/v1/**'
      - 'node/javascript/v1/**'
      - 'node/typescript/v1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    env:
      REACT_APP_AMPLITUDE_API_KEY: 'ampli-examples-test-api-key'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Node JS V1 - Install
        working-directory: node/javascript/v1/AmpliApp
        run: yarn install --frozen-lockfile

      - name: Node JS V1 - Test
        working-directory: node/javascript/v1/AmpliApp
        run: yarn test

      - name: Browser JS V1 - Install
        working-directory: browser/javascript/v1/react-app
        run: yarn install --frozen-lockfile

      - name: Browser JS V1 - Build
        working-directory: browser/javascript/v1/react-app
        run: yarn build

      - name: Browser JS V1 - Test
        working-directory: browser/javascript/v1/react-app
        run: yarn test

      - name: Node TS V1 - Install
        working-directory: node/typescript/v1/AmpliApp
        run: yarn install --frozen-lockfile

      - name: Node TS V1 - Test
        working-directory: node/typescript/v1/AmpliApp
        run: yarn test

      - name: Browser TS V1 - Install
        working-directory: browser/typescript/v1/react-app
        run: yarn install --frozen-lockfile

      - name: Browser TS V1 - Build
        working-directory: browser/typescript/v1/react-app
        run: yarn build

      - name: Browser TS V1 - Test
        working-directory: browser/typescript/v1/react-app
        run: yarn test
