name: CI - Android Tests

on:
  pull_request:
    paths:
      - 'android/kotlin/v1/**'
      - 'android/kotlin/v2/**' 
      - 'android/java/v2/**'
      - 'android/java/v2/**'

jobs:
  test:
    name: Test Android Kotlin/Java
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Kotlin V1 Tests
        working-directory: ./android/kotlin/v1/AmpliApp
        run: |
          ./gradlew build

      - name: Stop gradlew daemon for Kotlin V1
        working-directory: ./android/kotlin/v1/AmpliApp
        run: |
          ./gradlew --stop

      - name: Run Kotlin V2 Tests
        working-directory: ./android/kotlin/v2/AmpliApp
        run: |
          ./gradlew build

      - name: Stop gradlew daemon for Kotlin V2
        working-directory: ./android/kotlin/v2/AmpliApp
        run: |
          ./gradlew --stop

      - name: Run Java V1 Tests
        working-directory: ./android/java/v1/AmpliApp
        run: |
          ./gradlew build

      - name: Stop gradlew daemon for Java V1
        working-directory: ./android/java/v1/AmpliApp
        run: |
          ./gradlew --stop

      - name: Run Java V1 Tests
        working-directory: ./android/java/v2/AmpliApp
        run: |
          ./gradlew build

      - name: Stop gradlew daemon for Java V2
        working-directory: ./android/java/v2/AmpliApp
        run: |
          ./gradlew --stop
