name: CI - React Native V1 Tests

on:
  pull_request:
    paths:
      - 'react-native/typescript/v1/**'
      - 'react-native/javascript/v1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: TS - Install
        working-directory: react-native/typescript/v1/AmpliApp
        run: yarn install --frozen-lockfile

      - name: TS - Test
        working-directory: react-native/typescript/v1/AmpliApp
        run: yarn test

      - name: JS - Install
        working-directory: react-native/javascript/v1/AmpliApp
        run: yarn install --frozen-lockfile

      - name: JS - Test
        working-directory: react-native/javascript/v1/AmpliApp
        run: yarn test
