name: CI - iOS V2 Tests

on:
  pull_request:
    paths:
      - 'ios/objective-c/v2/**'
      - 'ios/swift/v2/**'

jobs:
  test:
    name: Test
    runs-on: macos-12
    strategy:
      matrix:
        ruby-version: ["2.7.x"]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set Xcode 14.2
        run: |
          sudo xcode-select -switch /Applications/Xcode_14.2.app

      - name: Swift iOS Tests
        working-directory: ./ios/swift/v2/AmpliSwiftSampleApp
        run: |
          xcodebuild test \
            -project AmpliSwiftSampleApp.xcodeproj \
            -scheme AmpliSwiftSampleAppTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'

      - name: Objective-C iOS Tests
        working-directory: ./ios/objective-c/v2/AmpliObjectiveCSampleApp
        run: |
          xcodebuild test \
            -project AmpliObjectiveCSampleApp.xcodeproj \
            -scheme AmpliObjectiveCSampleApp \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
