name: CI - Python Tests

on:
  pull_request:
    paths:
      - 'python/**'

jobs:
  test:
    name: Test Python Ampli
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: "3.6"

      - name: Run Python Simple Tests
        working-directory: python/simple/v1
        run: |
          pip install -r requirements.txt
          cp .env.example .env
          python -m unittest test_ampli.py

      - name: Run Python Django Tests
        working-directory: python/django/v1
        run: |
          pip install django
          cp ampli_app/.env.example ampli_app/.env
          python manage.py test
