def import_pods

pod 'Amplitude', "~> 8.10.0"

end

inhibit_all_warnings!

target 'AmpliObjectiveCSampleApp' do
    platform :ios, '15.0'
    project "AmpliObjectiveCSampleApp"

    import_pods
end

target 'AmpliObjectiveCSampleAppTests' do
    platform :ios, '15.0'
    project "AmpliObjectiveCSampleApp"

    import_pods
end
