//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

import java.io.IOException;

/**
 * Description for enum with space
 */
public enum EnumWithSpace {
    ENUM_WITH_SPACE;

    public String toValue() {
        switch (this) {
            case ENUM_WITH_SPACE: return "enum with space";
        }
        return null;
    }

    public static EnumWithSpace forValue(String value) throws IOException {
        if (value.equals("enum with space")) return ENUM_WITH_SPACE;
        throw new IOException("Cannot deserialize EnumWithSpace");
    }
}
