//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

public class EventWithOptionalProperties extends Event {
    public EventWithOptionalProperties(
        EventWithOptionalPropertiesProperties eventProperties
    ) {
        super("Event With Optional Properties");
        if (eventProperties.getOptionalArrayNumber() != null) { this.addProperty("optionalArrayNumber", eventProperties.getOptionalArrayNumber()); }
        if (eventProperties.getOptionalArrayString() != null) { this.addProperty("optionalArrayString", eventProperties.getOptionalArrayString()); }
        if (eventProperties.getOptionalBoolean() != null) { this.addProperty("optionalBoolean", eventProperties.getOptionalBoolean()); }
        if (eventProperties.getOptionalNumber() != null) { this.addProperty("optionalNumber", eventProperties.getOptionalNumber()); }
        if (eventProperties.getOptionalString() != null) { this.addProperty("optionalString", eventProperties.getOptionalString()); }
    }
}
