//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

public class EventWithConstTypes extends Event {
    public EventWithConstTypes() {
        super("Event With Const Types");
        this.addProperty("Boolean Const", true);
        this.addProperty("Integer Const", 10);
        this.addProperty("Number Const", 2.2);
        this.addProperty("String Const", "String-Constant");
        this.addProperty("String Const WIth Quotes", "\"String \"Const With\" Quotes\"");
        this.addProperty("String Int Const", 0);
    }
}
