//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull java-ampli'
//
// Required dependencies: com.amplitude:android-sdk:2.34.1, com.squareup.okhttp3:okhttp:4.2.2
// Tracking Plan Version: 0
// Build: 1.0.0
//
// [View Tracking Plan](https://data.amplitude.com/test-codegen/Test%20Codegen/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/test-codegen/Test%20Codegen/implementation/java-ampli)
//
package com.amplitude.ampli;

public class IdentifyProperties {
    private String[] optionalArray;
    private double requiredNumber;

    /**
     * Description for identify optionalArray
     */
    public String[] getOptionalArray() { return optionalArray; }
    public void setOptionalArray(String[] value) { this.optionalArray = value; }

    /**
     * Description for identify requiredNumber
     */
    public double getRequiredNumber() { return requiredNumber; }
    public void setRequiredNumber(double value) { this.requiredNumber = value; }
}
